'use client'

import { useEffect, useState } from 'react'

import {
  RotateCcw,
  Volume2,
  Sparkles,
  Heart,
} from 'lucide-react'

type Flashcard = {
  japanese: string
  english: string
  pronunciation: string
}

export default function FlashcardsPage() {
  const [card, setCard] =
    useState<Flashcard | null>(null)

  const [loading, setLoading] =
    useState(false)

  const [saved, setSaved] =
    useState(false)

  const generateCard = async () => {
    setLoading(true)

    try {
      const response = await fetch(
        '/api/flashcard'
      )

      const data = await response.json()

      setCard(data)

      const existing =
        JSON.parse(
          localStorage.getItem(
            'kotoba-favorites'
          ) || '[]'
        )

      const alreadySaved =
        existing.find(
          (item: Flashcard) =>
            item.japanese ===
            data.japanese
        )

      setSaved(!!alreadySaved)
    } catch (error) {
      console.log(error)
    }

    setLoading(false)
  }

  useEffect(() => {
    generateCard()
  }, [])

  const speakJapanese = () => {
    if (!card) return

    const utterance =
      new SpeechSynthesisUtterance(
        card.japanese
      )

    utterance.lang = 'ja-JP'

    window.speechSynthesis.speak(
      utterance
    )
  }

  const saveFavorite = () => {
    if (!card) return

    const existing =
      JSON.parse(
        localStorage.getItem(
          'kotoba-favorites'
        ) || '[]'
      )

    const alreadySaved =
      existing.find(
        (item: Flashcard) =>
          item.japanese ===
          card.japanese
      )

    if (alreadySaved) {
      const updated =
        existing.filter(
          (item: Flashcard) =>
            item.japanese !==
            card.japanese
        )

      localStorage.setItem(
        'kotoba-favorites',
        JSON.stringify(updated)
      )

      setSaved(false)

      return
    }

    existing.push(card)

    localStorage.setItem(
      'kotoba-favorites',
      JSON.stringify(existing)
    )

    setSaved(true)
  }

  return (
    <div className="min-h-screen bg-[#f8f4ef] p-6 text-black md:p-10">
      <div className="mx-auto max-w-5xl">
        {/* Header */}

        <div className="flex items-center gap-4">
          <div className="rounded-3xl bg-black p-4 text-white shadow-xl">
            <Sparkles />
          </div>

          <div>
            <h1 className="text-5xl font-bold">
              AI Flashcards
            </h1>

            <p className="mt-2 text-black/60">
              Learn random Japanese words
              generated by AI.
            </p>
          </div>
        </div>

        {/* Flashcard */}

        <div className="mt-14 flex justify-center">
          <div className="w-full max-w-2xl rounded-[2.5rem] bg-white p-10 shadow-2xl">
            {loading ? (
              <div className="flex h-[350px] items-center justify-center">
                <p className="text-2xl font-semibold">
                  Generating AI card...
                </p>
              </div>
            ) : (
              <div className="flex min-h-[350px] flex-col items-center justify-center text-center">
                <p className="text-7xl font-bold">
                  {card?.japanese}
                </p>

                <p className="mt-6 text-2xl text-black/60">
                  {card?.pronunciation}
                </p>

                <div className="mt-10 rounded-3xl bg-pink-100 px-8 py-5">
                  <p className="text-3xl font-bold">
                    {card?.english}
                  </p>
                </div>

                <p className="mt-8 text-black/40">
                  AI-generated learning card
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Buttons */}

        <div className="mt-10 flex flex-wrap justify-center gap-4">
          <button
            onClick={speakJapanese}
            className="flex items-center gap-2 rounded-2xl bg-black px-7 py-4 text-white transition hover:scale-105"
          >
            <Volume2 size={20} />
            Pronounce
          </button>

          <button
            onClick={generateCard}
            className="flex items-center gap-2 rounded-2xl bg-pink-400 px-7 py-4 font-semibold text-white transition hover:scale-105"
          >
            <RotateCcw size={20} />
            Generate New Card
          </button>

          <button
            onClick={saveFavorite}
            className={`flex items-center gap-2 rounded-2xl px-7 py-4 font-semibold text-white transition hover:scale-105 ${
              saved
                ? 'bg-red-500'
                : 'bg-black'
            }`}
          >
            <Heart size={20} />

            {saved
              ? 'Saved'
              : 'Save Favorite'}
          </button>
        </div>
      </div>
    </div>
  )
}